import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import '@/components/SpinningCards.css'
import '@/components/CardNav.css'
import CardNav from "@/components/CardNav";
import { items } from "@/components/CardNavItems";

const ttCommons = localFont({
  src: [
    {
      path: './fonts/TT-Commons-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/TT-Commons-Medium.otf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: "--font-tt-commons",
})

const grift = localFont({
  src: [
    {
      path: "./fonts/grift-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/grift-medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-grift",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grift.variable} ${ttCommons.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CardNav
          logo="/slice1.svg"
          items={items}
        />
        {children}
      </body>
    </html>
  );
}
